<?php

use Illuminate\Database\Seeder;
use App\Model\Room;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $room = [
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '1', 'city' => '1', 'station' => '1', 'train1' => '3', 'room_name' => 'グレンドール新宿マンション', 'room_py' => '31.52', 'type' => '1LDK', 'price' => '10'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '1', 'station' => '1', 'train1' => '3', 'room_name' => 'プラウド新宿マンション', 'room_py' => '44.49', 'type' => '1LDK', 'price' => '8'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house1.jpeg', 'prefecture' => '1', 'city' => '1', 'station' => '1', 'train1' => '3', 'room_name' => 'オープンライブス', 'room_py' => '99.24', 'type' => '2LDK+S', 'price' => '20'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house2.jpeg', 'prefecture' => '1', 'city' => '1', 'station' => '1', 'train1' => '3', 'room_name' => '中井１', 'room_py' => '42.08', 'type' => '3LDK', 'price' => '10.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '1', 'station' => '1', 'train1' => '3', 'room_name' => '朝日プラザマンション', 'room_py' => '28.52', 'type' => '1DK', 'price' => '9'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '2', 'station' => '2', 'train1' => '3', 'room_name' => 'メゾンドール北参道', 'room_py' => '30.88', 'type' => '1K', 'price' => '9.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion3.png', 'prefecture' => '1', 'city' => '2', 'station' => '2', 'train1' => '3', 'room_name' => 'シャトレーイン', 'room_py' => '14.52', 'type' => '1K', 'price' => '11'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '2', 'station' => '2', 'train1' => '3', 'room_name' => 'コーポマンション', 'room_py' => '44.53', 'type' => '1LDK', 'price' => '8'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house1.jpeg', 'prefecture' => '1', 'city' => '2', 'station' => '2', 'train1' => '3', 'room_name' => 'フェニックス西参道', 'room_py' => '20.76', 'type' => '1K', 'price' => '7.6'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '1', 'city' => '2', 'station' => '2', 'train1' => '3', 'room_name' => 'パークハビオ', 'room_py' => '38.21', 'type' => '1LDK', 'price' => '12'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '1', 'city' => '2', 'station' => '2', 'train1' => '3', 'room_name' => 'カーサスプレンディッド', 'room_py' => '44.7', 'type' => '2LDK', 'price' => '20.2'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '3', 'station' => '3', 'train1' => '3', 'room_name' => 'クリオ', 'room_py' => '40.24', 'type' => '1LDK', 'price' => '13.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion3.png', 'prefecture' => '1', 'city' => '3', 'station' => '3', 'train1' => '3', 'room_name' => 'スカイコートパレス', 'room_py' => '20.42', 'type' => '1K', 'price' => '8.15'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '3', 'station' => '3', 'train1' => '3', 'room_name' => 'クレストコート', 'room_py' => '35.93', 'type' => '1LDK', 'price' => '15.1'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '3', 'station' => '3', 'train1' => '3', 'room_name' => 'Cielo', 'room_py' => '20.32', 'type' => '1K', 'price' => '7.6'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '1', 'city' => '3', 'station' => '3', 'train1' => '3', 'room_name' => 'AIFLAT', 'room_py' => '33.96', 'type' => '1LDK', 'price' => '12'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '1', 'city' => '3', 'station' => '3', 'train1' => '3', 'room_name' => 'ロイヤルハイツ', 'room_py' => '56.2', 'type' => '2LDK', 'price' => '12.4'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'ベルファース', 'room_py' => '19.24', 'type' => '1K', 'price' => '8.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'オジオ', 'room_py' => '30.24', 'type' => '1LDK', 'price' => '13.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'レジディア', 'room_py' => '40.05', 'type' => '2LDK', 'price' => '17.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'S-RESIDENCE', 'room_py' => '50.24', 'type' => '3LDK', 'price' => '23'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'パレステュディオ', 'room_py' => '25.2', 'type' => '1DK', 'price' => '9.2'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'パークキューブ', 'room_py' => '30.5', 'type' => '2DK', 'price' => '10'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion3.png', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'スカイコート', 'room_py' => '40.24', 'type' => '1LDK', 'price' => '9.5'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house3.jpeg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'ベルファース', 'room_py' => '19.24', 'type' => '1K', 'price' => '8.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house1.jpeg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'オジオ', 'room_py' => '30.24', 'type' => '1LDK', 'price' => '13.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'レジディア', 'room_py' => '40.05', 'type' => '2LDK', 'price' => '17.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'S-RESIDENCE', 'room_py' => '50.24', 'type' => '3LDK', 'price' => '23'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'パレステュディオ', 'room_py' => '25.2', 'type' => '1DK', 'price' => '9.2'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'パークキューブ', 'room_py' => '30.5', 'type' => '2DK', 'price' => '10'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '1', 'city' => '4', 'station' => '4', 'train1' => '3', 'train2' => '2', 'room_name' => 'スカイコート', 'room_py' => '40.24', 'type' => '1LDK', 'price' => '9.5'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '5', 'station' => '5', 'train1' => '3', 'train2' => '2', 'room_name' => 'ベルファース', 'room_py' => '19.24', 'type' => '1K', 'price' => '8.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '5', 'station' => '5', 'train1' => '3', 'train2' => '2', 'room_name' => 'オジオ', 'room_py' => '30.24', 'type' => '1LDK', 'price' => '13.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '5', 'station' => '5', 'train1' => '3', 'train2' => '2', 'room_name' => 'レジディア', 'room_py' => '40.05', 'type' => '2LDK', 'price' => '17.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '1', 'city' => '5', 'station' => '5', 'train1' => '3', 'train2' => '2', 'room_name' => 'S-RESIDENCE', 'room_py' => '50.24', 'type' => '3LDK', 'price' => '23'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house3.jpeg', 'prefecture' => '1', 'city' => '5', 'station' => '5', 'train1' => '3', 'train2' => '2', 'room_name' => 'パレステュディオ', 'room_py' => '25.2', 'type' => '1DK', 'price' => '9.2'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house1.jpeg', 'prefecture' => '1', 'city' => '5', 'station' => '5', 'train1' => '3', 'train2' => '2', 'room_name' => 'パークキューブ', 'room_py' => '30.5', 'type' => '2DK', 'price' => '10'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '1', 'city' => '5', 'station' => '5', 'train1' => '3', 'train2' => '2', 'room_name' => 'スカイコート', 'room_py' => '40.24', 'type' => '1LDK', 'price' => '9.5'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '6', 'station' => '6', 'train1' => '3','room_name' => 'ＭＡＮＯＡ', 'room_py' => '50.5', 'type' => '1LDK', 'price' => '15.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '6', 'station' => '6', 'train1' => '3','room_name' => 'レジディア', 'room_py' => '97.73', 'type' => '3LDK', 'price' => '44.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '1', 'city' => '6', 'station' => '6', 'train1' => '3','room_name' => 'レジディアスカイコート', 'room_py' => '26.24', 'type' => '1DK', 'price' => '11.2'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house2.jpeg', 'prefecture' => '1', 'city' => '6', 'station' => '6', 'train1' => '3','room_name' => 'シティハウス', 'room_py' => '62.49', 'type' => '2LDK', 'price' => '29.5'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion3.png', 'prefecture' => '1', 'city' => '6', 'station' => '6', 'train1' => '3','room_name' => 'エディアン', 'room_py' => '39.91', 'type' => '1LDK', 'price' => '15.8'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '1', 'city' => '7', 'station' => '7', 'train1' => '1', 'train2' => '2', 'room_name' => 'SPOLOK', 'room_py' => '61.47', 'type' => '2LDK', 'price' => '12'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house2.jpeg', 'prefecture' => '1', 'city' => '7', 'station' => '7', 'train1' => '1', 'train2' => '2', 'room_name' => 'シャルムウキマ', 'room_py' => '62.73', 'type' => '3LDK', 'price' => '11'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '1', 'city' => '7', 'station' => '7', 'train1' => '1', 'train2' => '2', 'room_name' => 'イイノコーポ', 'room_py' => '44.21', 'type' => '2LDK', 'price' => '7.9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '7', 'station' => '7', 'train1' => '1', 'train2' => '2', 'room_name' => 'プランタンカミヤ', 'room_py' => '57.75', 'type' => '2LDK', 'price' => '11.7'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '7', 'station' => '7', 'train1' => '1', 'train2' => '2', 'room_name' => 'ソワーニュ', 'room_py' => '40.99', 'type' => '1LDK', 'price' => '9.5'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'タウンハウス', 'room_py' => '36.4', 'type' => '1LDK', 'price' => '8'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'ＭＡＣ青南マンション', 'room_py' => '62.73', 'type' => '1LDK', 'price' => '14'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion3.png', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => '秀和イイノコーポ', 'room_py' => '33.75', 'type' => '1DK', 'price' => '9.9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => '南青山スカイハイツ', 'room_py' => '30.6', 'type' => '1DK', 'price' => '10.7'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'スカイコート', 'room_py' => '32.17', 'type' => '1LDK', 'price' => '9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => '中央マンション', 'room_py' => '44.05', 'type' => '2LDK', 'price' => '12'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'グランドメゾン', 'room_py' => '41.41', 'type' => '2DK', 'price' => '13'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house1.jpeg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'ナショナルコート', 'room_py' => '44.21', 'type' => '2LDK', 'price' => '17.9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house2.jpeg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'セントラルハイツ', 'room_py' => '57.75', 'type' => '2LDK', 'price' => '11.7'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house3.jpeg', 'prefecture' => '1', 'city' => '8', 'station' => '8', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'ロイヤルプラザ', 'room_py' => '40.99', 'type' => '1LDK', 'price' => '9.5'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'ニックハイム', 'room_py' => '36.4', 'type' => '1LDK', 'price' => '8'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'ニューハイツ', 'room_py' => '62.73', 'type' => '1LDK', 'price' => '14'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion3.png', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'タウンプラザ', 'room_py' => '33.75', 'type' => '1DK', 'price' => '9.9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => '太平洋戸越マンション', 'room_py' => '30.6', 'type' => '1DK', 'price' => '10.7'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'セブンスターマンション', 'room_py' => '32.17', 'type' => '1LDK', 'price' => '9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'ストークマンション', 'room_py' => '44.05', 'type' => '2LDK', 'price' => '12'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'サマリヤマンション', 'room_py' => '41.41', 'type' => '2DK', 'price' => '13'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house1.jpeg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => 'シャンボール', 'room_py' => '44.21', 'type' => '2LDK', 'price' => '17.9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house2.jpeg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => '第1コーポラス', 'room_py' => '57.75', 'type' => '2LDK', 'price' => '11.7'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house3.jpeg', 'prefecture' => '1', 'city' => '9', 'station' => '9', 'train1' => '1', 'train2' => '2', 'train3' => '3', 'room_name' => '第2コーポラス', 'room_py' => '40.99', 'type' => '1LDK', 'price' => '9.5'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '1', 'city' => '10', 'station' => '10', 'train1' => '1', 'train2' => '2', 'room_name' => 'ハイタウン', 'room_py' => '61.47', 'type' => '2LDK', 'price' => '12'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '1', 'city' => '10', 'station' => '10', 'train1' => '1', 'train2' => '2', 'room_name' => 'フラワーマンション', 'room_py' => '62.73', 'type' => '3LDK', 'price' => '11'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion4.jpg', 'prefecture' => '1', 'city' => '10', 'station' => '10', 'train1' => '1', 'train2' => '2', 'room_name' => 'パレス羽田', 'room_py' => '44.21', 'type' => '2LDK', 'price' => '7.9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '1', 'city' => '10', 'station' => '10', 'train1' => '1', 'train2' => '2', 'room_name' => 'オークヒルズ', 'room_py' => '57.75', 'type' => '2LDK', 'price' => '11.7'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '1', 'city' => '10', 'station' => '10', 'train1' => '1', 'train2' => '2', 'room_name' => 'コーポビアネーズ', 'room_py' => '40.99', 'type' => '1LDK', 'price' => '9.5'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales3.jpg', 'prefecture' => '2', 'city' => '11', 'station' => '11', 'train1' => '1', 'train2' => '2', 'room_name' => 'ミールマンション', 'room_py' => '49.55', 'type' => '2DK', 'price' => '12'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '2', 'city' => '11', 'station' => '11', 'train1' => '1', 'train2' => '2', 'room_name' => 'エンゼルハイム', 'room_py' => '62.73', 'type' => '3LDK', 'price' => '20'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '2', 'city' => '11', 'station' => '11', 'train1' => '1', 'train2' => '2', 'room_name' => 'ライオンズマンション', 'room_py' => '44.21', 'type' => '1LDK', 'price' => '7.9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '2', 'city' => '11', 'station' => '11', 'train1' => '1', 'train2' => '2', 'room_name' => 'ルミネ', 'room_py' => '57.75', 'type' => '2LDK', 'price' => '11.7'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion3.png', 'prefecture' => '2', 'city' => '11', 'station' => '11', 'train1' => '1', 'train2' => '2', 'room_name' => 'クリオ', 'room_py' => '40.99', 'type' => '1LDK', 'price' => '9.5'],

            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales2.jpg', 'prefecture' => '2', 'city' => '12', 'station' => '12', 'train1' => '1', 'train2' => '2', 'room_name' => 'エンゼルハイ', 'room_py' => '61.47', 'type' => '4LDK', 'price' => '22'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion2.jpeg', 'prefecture' => '2', 'city' => '12', 'station' => '12', 'train1' => '1', 'train2' => '2', 'room_name' => 'アイランドグレース', 'room_py' => '62.73', 'type' => '1LDK', 'price' => '11'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/manshion1.jpeg', 'prefecture' => '2', 'city' => '12', 'station' => '12', 'train1' => '1', 'train2' => '2', 'room_name' => 'グランシティ', 'room_py' => '44.21', 'type' => '2LDK', 'price' => '7.9'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/leopales1.jpg', 'prefecture' => '2', 'city' => '12', 'station' => '12', 'train1' => '1', 'train2' => '2', 'room_name' => 'リヴァリエ', 'room_py' => '57.75', 'type' => '2DK', 'price' => '11.7'],
            ['roomImg_url' => 'https://jhprojectbucket.s3-ap-northeast-1.amazonaws.com/sumitomo/house1.jpeg', 'prefecture' => '2', 'city' => '12', 'station' => '12', 'train1' => '1', 'train2' => '2', 'room_name' => 'パールハイム', 'room_py' => '40.99', 'type' => '1LDK', 'price' => '9.5']
        ];
        foreach ($room as $data) {
            Room::create($data);
        }
    }
}
